import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description: "Terms and Conditions for using CricPost — the free cricket poster and meme maker.",
  robots: { index: true, follow: true },
  alternates: { canonical: "https://cricpost.in/terms" },
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6">
      <h1 className="mb-2 text-3xl font-bold">Terms &amp; Conditions</h1>
      <p className="mb-10 text-sm text-muted-foreground">Last updated: March 2026</p>

      <div className="space-y-8 text-sm leading-relaxed text-muted-foreground">

        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">1. Acceptance of Terms</h2>
          <p>
            By accessing or using CricPost (<strong className="text-foreground">cricpost.in</strong>), you agree to be
            bound by these Terms &amp; Conditions. If you do not agree with any part of these terms, please do not use
            the website.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">2. No Affiliation with BCCI / IPL</h2>
          <p>
            CricPost is an independent, fan-made tool. We are <strong className="text-foreground">not affiliated with,
            endorsed by, or connected to</strong> the Board of Control for Cricket in India (BCCI), Indian Premier
            League (IPL), any IPL franchise, or any official cricket body. All team names, logos, and player images
            remain the intellectual property of their respective owners.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">3. Third-Party Content &amp; Images</h2>
          <p>
            Player images, team logos, and other media displayed on CricPost are sourced from publicly available
            resources and belong to their respective copyright owners. CricPost does not claim ownership of any such
            content. If you are a rights holder and believe your content is being used improperly, please contact us
            and we will address it promptly.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">4. User-Generated Content</h2>
          <p>
            Posters, cards, and memes created using CricPost are generated by you, the user. You are solely responsible
            for any content you create, download, or share. CricPost takes no responsibility for how you use or
            distribute the content produced through this tool. You must not use the tool to create content that is
            defamatory, misleading, offensive, or infringes any third-party rights.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">5. Disclaimer of Warranties</h2>
          <p>
            CricPost is provided <strong className="text-foreground">&ldquo;as is&rdquo;</strong> without warranties of
            any kind, express or implied. We do not warrant that the service will be uninterrupted, error-free, or free
            of viruses. We make no guarantees regarding the accuracy, completeness, or timeliness of match schedules,
            player statistics, or any other data displayed on the site.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">6. Limitation of Liability</h2>
          <p>
            To the fullest extent permitted by law, CricPost, its creators, and contributors shall{" "}
            <strong className="text-foreground">not be liable</strong> for any direct, indirect, incidental, special,
            consequential, or punitive damages arising out of or in connection with:
          </p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Your use of or inability to use the website or its features</li>
            <li>Any content you download or share using the tool</li>
            <li>Any errors or inaccuracies in data (match schedules, scores, player info)</li>
            <li>Any unauthorised access to or alteration of your data</li>
            <li>Any third-party content or services linked from this site</li>
          </ul>
          <p className="mt-3">
            Use of this website is entirely at your own risk.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">7. Data &amp; Privacy</h2>
          <p>
            Business details (name, phone, logo) entered on CricPost are stored locally in your browser and optionally
            in your account profile. We do not sell or share your personal information with third parties. By using
            optional account features, you agree to our data handling practices as described above.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">8. Permitted Use</h2>
          <p>You may use CricPost to:</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Create and download cricket-themed posters for personal or business promotional use</li>
            <li>Share generated images on social media or messaging platforms</li>
          </ul>
          <p className="mt-3">You may <strong className="text-foreground">not</strong>:</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Reproduce, redistribute, or resell the platform itself</li>
            <li>Scrape, copy, or mirror the website&apos;s content or data</li>
            <li>Use the tool for any unlawful, harmful, or fraudulent purpose</li>
            <li>Misrepresent generated content as official BCCI / IPL material</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">9. Changes to These Terms</h2>
          <p>
            We reserve the right to update these Terms &amp; Conditions at any time. Changes will be posted on this
            page with an updated date. Continued use of the site after changes are posted constitutes your acceptance
            of the revised terms.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-base font-semibold text-foreground">10. Contact</h2>
          <p>
            For any questions or concerns regarding these terms, please reach out via our social channels or the
            contact information listed on the website.
          </p>
        </section>

      </div>
    </div>
  );
}
